version: "3.7"

services:
  database:
    image: postgres
    container_name: perfect_beer_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=nelsondev
      - POSTGRES_DB=perfect_beer
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: perfect_beer_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app 
volumes:
  pgdata: 